name: ci

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test

      - name: Build Linux
        run: go build -o brainfuck -v .

      - name: Build Windows
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'shilangyu/brainfuck'
        continue-on-error: true
        run: GOOS=windows GOARCH=386 go build -o brainfuck.exe -v .

      - name: Build OSX
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'shilangyu/brainfuck'
        continue-on-error: true
        run: GOOS=darwin GOARCH=amd64 go build -o brainfuck.dmg -v .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'shilangyu/brainfuck'
        with:
          files: |
            brainfuck
            brainfuck.exe
            brainfuck.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
